### ISSUE TITLE
Limit to the preemptive optimistic caching behaviour

### ISSUE THREAD

**Issue by danielloader** [naughtygopher/pocache#7]
Looking good, promising project.

Wondered if you'd think it was worth including a capacity to either have a counter or duration for 'idle' timeout.

### Use Case

I'd like to cache bearer token oauth2 introspections, and the idea of pre-warming that and saving myself 100ms latency hit on my backend gin middleware sounds appealing - but if I couldn't set how long a cache value is kept warm for I'd just eventually cause a spiralling amount of calls to my oauth2 provider. 

Currently I'm just using Redis directly to cache these, but obviously they expire after x seconds (60s for me currently) and next hit after that incurs a cold start penalty to populate the cache before it's then kept for the next 60s.

Would be good if there's only the first penalty of the first login of the day and then set an 8 hour window to keep re-validating that session permission data every x seconds, but after that y hour window elapses the cache stops trying to pre-warm the data. 

Just thinking out loud of a feature I don't currently have but would like, currently the only other option I have is extending the ttl value and serving more stale data than I'd like (for when permissions claims on the token change).

Conversely could just take an int value as a multiple, so it will refresh z times in the background multiplied by the expiry time subtracting the revalidation time.

**Comment by bnkamalesh** [comment]
hello @danielloader, it's  indeed an interesting usecase, which would require a cronjob/scheduler to solve. In my opinion, I think this is better handled outside of this package, since you anyway can customize the updater, or even the store.  So you have the hooks available at almost all stages.

p.s: I assume you already found a solution since you closed the issue.

**Comment by danielloader** [comment]
Yeah I realised the same as you did this is best handled via some hooks.

Thanks for replying
