### ISSUE TITLE
Should updater be an exported type?

### ISSUE THREAD

**Issue by danielloader** [naughtygopher/pocache#8]
Tying to initialise a cache but want to pass in an updater function on a NewCache method on a struct where the cache is stored but can't easily due to the type not being exported where as ErrOnUpdate is.

Currently just vendoring my own type in the same file by copy/pasting it from the source.

**Comment by bnkamalesh** [comment]
Yes that makes sense. I've fixed it here https://github.com/naughtygopher/pocache/pull/9.
